apiVersion: 1

datasources:
  - name: pollen-postgresql-datasource
    uid: cdzgle8mf6dc0b 
    orgId: 1
    type: postgres
    access: proxy
    url: postgres:5432
    database: pollen
    user: postgres
    basicAuth: false
    secureJsonData:
      password: "mysecretpassword"
    jsonData:
      sslmode: "disable"
      tlsAuth: false
      tlsAuthWithCACert: false
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
    isDefault: true